from alembic import op
import sqlalchemy as sa

revision = "20260908_0025"
down_revision = "20260908_0024"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("expert_sources", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False), sa.Column("source_key", sa.String(length=50), nullable=False), sa.Column("author_name", sa.String(length=255), nullable=True), sa.Column("author_handle", sa.String(length=255), nullable=False), sa.Column("profile_url", sa.String(length=2048), nullable=True), sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("length(trim(source_key)) > 0", name="ck_expert_sources_source_key_nonblank"), sa.CheckConstraint("source_key = upper(source_key)", name="ck_expert_sources_source_key_uppercase"), sa.CheckConstraint("length(trim(author_handle)) > 0", name="ck_expert_sources_author_handle_nonblank"), sa.CheckConstraint("author_name IS NULL OR length(trim(author_name)) > 0", name="ck_expert_sources_author_name_null_or_nonblank"), sa.CheckConstraint("profile_url IS NULL OR length(trim(profile_url)) > 0", name="ck_expert_sources_profile_url_null_or_nonblank"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("source_key", "author_handle", name="uq_expert_sources_source_handle"), sa.UniqueConstraint("id", "source_key", name="uq_expert_sources_id_source_key"))
    op.create_index("ix_expert_sources_active_source_handle_id", "expert_sources", ["is_active", "source_key", "author_handle", "id"])
    op.create_table("user_expert_sources", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False), sa.Column("user_id", sa.Integer(), nullable=False), sa.Column("expert_source_id", sa.Integer(), nullable=False), sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.ForeignKeyConstraint(["user_id"], ["users.id"]), sa.ForeignKeyConstraint(["expert_source_id"], ["expert_sources.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("user_id", "expert_source_id", name="uq_user_expert_sources_user_source"))
    op.create_index("ix_user_expert_sources_user_id_id", "user_expert_sources", ["user_id", "id"])
    op.create_table("sentiment_posts", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False), sa.Column("expert_source_id", sa.Integer(), nullable=False), sa.Column("source_key", sa.String(length=50), nullable=False), sa.Column("external_id", sa.String(length=255), nullable=True), sa.Column("url", sa.String(length=2048), nullable=True), sa.Column("canonical_url", sa.String(length=2048), nullable=True), sa.Column("title", sa.String(length=500), nullable=True), sa.Column("content", sa.Text(), nullable=False), sa.Column("author_name", sa.String(length=255), nullable=True), sa.Column("author_handle", sa.String(length=255), nullable=True), sa.Column("published_at", sa.DateTime(timezone=True), nullable=False), sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False), sa.Column("content_type", sa.String(length=20), nullable=False), sa.Column("language", sa.String(length=16), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("length(trim(source_key)) > 0", name="ck_sentiment_posts_source_key_nonblank"), sa.CheckConstraint("source_key = upper(source_key)", name="ck_sentiment_posts_source_key_uppercase"), sa.CheckConstraint("external_id IS NULL OR length(trim(external_id)) > 0", name="ck_sentiment_posts_external_id_null_or_nonblank"), sa.CheckConstraint("url IS NULL OR length(trim(url)) > 0", name="ck_sentiment_posts_url_null_or_nonblank"), sa.CheckConstraint("canonical_url IS NULL OR length(trim(canonical_url)) > 0", name="ck_sentiment_posts_canonical_url_null_or_nonblank"), sa.CheckConstraint("title IS NULL OR length(trim(title)) > 0", name="ck_sentiment_posts_title_null_or_nonblank"), sa.CheckConstraint("length(trim(content)) > 0", name="ck_sentiment_posts_content_nonblank"), sa.CheckConstraint("author_name IS NULL OR length(trim(author_name)) > 0", name="ck_sentiment_posts_author_name_null_or_nonblank"), sa.CheckConstraint("author_handle IS NULL OR length(trim(author_handle)) > 0", name="ck_sentiment_posts_author_handle_null_or_nonblank"), sa.CheckConstraint("length(trim(language)) > 0", name="ck_sentiment_posts_language_nonblank"), sa.CheckConstraint("content_type IN ('NEWS', 'RSS', 'SOCIAL')", name="ck_sentiment_posts_content_type"), sa.CheckConstraint("external_id IS NOT NULL OR canonical_url IS NOT NULL", name="ck_sentiment_posts_duplicate_identity"), sa.ForeignKeyConstraint(["expert_source_id", "source_key"], ["expert_sources.id", "expert_sources.source_key"], name="fk_sentiment_posts_expert_source_source_key"), sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_sentiment_posts_published_id", "sentiment_posts", ["published_at", "id"])
    op.create_index("uq_sentiment_posts_source_external_id", "sentiment_posts", ["source_key", "external_id"], unique=True, postgresql_where=sa.text("external_id IS NOT NULL"), sqlite_where=sa.text("external_id IS NOT NULL"))
    op.create_index("uq_sentiment_posts_source_canonical_url", "sentiment_posts", ["source_key", "canonical_url"], unique=True, postgresql_where=sa.text("external_id IS NULL AND canonical_url IS NOT NULL"), sqlite_where=sa.text("external_id IS NULL AND canonical_url IS NOT NULL"))


def downgrade() -> None:
    op.drop_index("uq_sentiment_posts_source_canonical_url", table_name="sentiment_posts")
    op.drop_index("uq_sentiment_posts_source_external_id", table_name="sentiment_posts")
    op.drop_index("ix_sentiment_posts_published_id", table_name="sentiment_posts")
    op.drop_table("sentiment_posts")
    op.drop_index("ix_user_expert_sources_user_id_id", table_name="user_expert_sources")
    op.drop_table("user_expert_sources")
    op.drop_index("ix_expert_sources_active_source_handle_id", table_name="expert_sources")
    op.drop_table("expert_sources")